cfdumpzilla:
        dall:
        dhistory: --History
        dbookmarks: --Bookmarks
        dcookies:
        dpermissions:
        ddownloads:
        dforms:
        dcacheoffline:
        dthumbnails:
        drange:
        daddons:
        dpasswords:
        dcertoverride:
        dsession:
        dwatch:
cfhindsight:
        hformat: -f xlsx
        houtput: -o /root/Desktop/aafedit/Case_Numbers/test
        hbrowser:
        hlog:
        htimezone:
        hdecrypt:
        hcache:
