cfdumpzilla: {Addons: null, All: null, Bookmarks: --Bookmarks, Cacheoffline: null,
  Certoverride: null, Cookies: --Cookies, Downloads: null, Forms: null, History: --History,
  Passwords: null, Permissions: null, Range: null, Session: null, Thumbnails: null,
  Watch: null}
